export const ACTIONS = {
  FETCH_CLIENTS: 'FETCH_CLIENTS',
  FETCH_CLIENT_BY_ID: 'FETCH_CLIENT_BY_ID',
  CREATE_CLIENT: 'CREATE_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  RESET_CLIENT: 'RESET_CLIENT',
  COUNT_CLIENTS: 'COUNT_CLIENTS',

  FETCH_SERVICES: 'FETCH_SERVICES',
  FETCH_SERVICE_BY_ID: 'FETCH_SERVICE_BY_ID',
  CREATE_SERVICE: 'CREATE_SERVICE',
  UPDATE_SERVICE: 'UPDATE_SERVICE',
  DELETE_SERVICE: 'DELETE_SERVICE',
  FETCH_SERVICES_BY_CLIENT_ID: 'FETCH_SERVICES_BY_CLIENT_ID',
  COUNT_SERVICES: 'COUNT_SERVICES',

  FETCH_COUNTRIES: 'FETCH_COUNTRIES',

  FETCH_SERVICES_COUNTRIES: 'FETCH_SERVICES_COUNTRIES',
  CREATE_SERVICE_COUNTRY: 'CREATE_SERVICE_COUNTRY',
  DELETE_SERVICE_COUNTRY: 'DELETE_SERVICE_COUNTRY',
  COUNT_SERVICES_PER_COUNTRY: 'COUNT_SERVICES_PER_COUNTRY'
}

