export const ACTIONS = {
  FETCH_CLIENTS: 'FETCH_CLIENTS',
  FETCH_CLIENT_BY_ID: 'FETCH_CLIENT_BY_ID',
  CREATE_CLIENT: 'CREATE_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
}

